### ISSUE TITLE
The Big To-Do List

### ISSUE THREAD

**Issue by tomrav** [critical-search/critical-search#1]
### UI Features
- [ ] - home page
- [ ] - search results
- [ ] - result page
- [ ] - mobile view for all the things

### Server Features
- [ ] - parse vtt subtitles (required for campaign 2)
- [ ] - server boot script

### Tech debt
- [ ] - separate client and server
- [ ] - dev/production builds

### Testing
- [ ] - server testing
- [ ] - ui testing
- [ ] - e2e?
